#!/usr/bin/env sh

set -e

FZF_TERMINAL="${FZF_TERMINAL:-$TERMINAL}"

if [ -z "$FZF_TERMINAL" ]; then
  echo "$(basename "$0") expects either FZF_TERMINAL or TERMINAL to be set." >&2
  exit 1
fi

fzf_dir="$(mktemp --directory --suffix '-fzf' -t)"
trap 'rm -rf "$fzf_dir"' EXIT

fzf_arguments_file="$fzf_dir/arguments"
fzf_return_code_pipe="$fzf_dir/return-code"

touch "$fzf_arguments_file"
chmod 600 "$fzf_arguments_file"
while [ "$#" -gt 0 ]; do
  echo "$1" >> "$fzf_arguments_file"
  shift
done

mkfifo -m 600 "$fzf_return_code_pipe"

$FZF_TERMINAL -- sh -c "xargs --arg-file '$fzf_arguments_file' --delimiter '\n' fzf < '/proc/$$/fd/0' > '/proc/$$/fd/1' 2> '/proc/$$/fd/2'; echo "'$?'" > '$fzf_return_code_pipe'" &

exit "$(cat "$fzf_return_code_pipe")"
